# Generated by Django 3.2.9 on 2021-11-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='roles',
            field=models.CharField(choices=[('FINANCE', 'Handle organization finance'), ('HR', 'Manages Human Resources'), ('Marketing', 'Market our products'), ('Research', 'Conducts operations research'), ('Engineer', 'Develop both software/hardware products')], max_length=30, null=True),
        ),
    ]
